[package]
name = "xls2csv"
version = "0.1.0"
edition = "2021"
authors = ["Nick Stone <nicholasestone@proton.me>"]
description = "Convert excel documents to CSV"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
office = "0.8.1"
